# Generated by Django 3.1.5 on 2021-01-10 00:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_assessment_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='mark',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
