# Generated by Django 3.1.5 on 2021-01-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_auto_20210109_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='total',
            field=models.PositiveSmallIntegerField(default=100),
            preserve_default=False,
        ),
    ]
